# Generated by Django 4.2.2 on 2024-06-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_periodicity_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAIL', 'Неуспешно')], max_length=100, verbose_name='Статус попытки'),
        ),
    ]
